manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
      #add mouse
    # - name: ftc 
    #  url-base: https://github.com/ftc
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      # remote: ftc 
      # revision: mouse-ftc 
      # import: app/west.yml
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config

# manifest:
#   remotes:
#     - name: zmkfirmware
#       url-base: https://github.com/zmkfirmware
#     - name: infused-kim
#       url-base: https://github.com/infused-kim
#   projects:
#     - name: zmk
#       remote: infused-kim
#       revision: my-changes/split-encoder
#       import: app/west.yml
#   self:
#     path: config
