manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/RimTanaka
  projects:
    - name: zmk
      remote: RimTanaka
      revision: main
      import: app/west.yml
  self:
    path: config
